=== dneuge/xprc-protocol/src/command.xsd
<?xml version='1.0' encoding='utf-8' ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--xs:import namespace="http://www.w3.org/XML/1998/namespace" /-->

    <xs:element name="command" type="Command">
        <xs:annotation>
            <xs:documentation>
                Describes a single command for protocol user documentation.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="Command">
        <xs:all>
            <xs:element name="mnemonic" type="Mnemonic">
                <xs:annotation>
                    <xs:documentation>
                        Describes how the command name is derived from a mnemonic description.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="Markdown">
                <xs:annotation>
                    <xs:documentation>
                        Main description; should provide an overview of what the command does and is intended for. Should not go into details regarding options or parameters. Side-effects and conditions may make sense to be described as notes instead to be more visible.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="options" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="option" type="Option" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="parameters" type="Parameters" minOccurs="0" />
            <xs:element name="responses">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="response" type="Markdown" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="notes" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Additional notes to be shown as bullet items.
                    </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="note" type="Markdown" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="examples" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="example" type="Example" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>

        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="title" type="xs:string" />
        <xs:attribute name="group" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Mnemonic" mixed="true">
        <xs:sequence>
            <xs:element name="m" type="xs:string" minOccurs="4" maxOccurs="4" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Option">
        <xs:sequence>
            <xs:element name="description" type="Markdown" />
            <xs:element name="suffixes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="suffix" type="OptionSuffix" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="constants" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="constant" type="OptionConstant" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="default" type="xs:string" />
        <xs:attribute name="defaultRemark" type="xs:string" />
        <xs:attribute name="variableName" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="OptionSuffix">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="OptionConstant">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Parameters">
        <xs:sequence>
            <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="subparameters" type="SubParameters" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SubParameters">
        <xs:sequence>
            <xs:element name="subparameters" type="SubParameters" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="delimiter" type="xs:string" />
        <xs:attribute name="multiplicity" default="1" type="ParameterMultiplicity" />
        <xs:attribute name="condition" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="multiplicity" default="1" type="ParameterMultiplicity" />
                <xs:attribute name="condition" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="ParameterMultiplicity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="?">
                <xs:annotation>
                    <xs:documentation>
                        The parameter is optional.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
                <xs:annotation>
                    <xs:documentation>
                        The parameter occurs exactly once.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="+">
                <xs:annotation>
                    <xs:documentation>
                        The parameter occurs at least once, can be repeated immediately afterwards.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="*">
                <xs:annotation>
                    <xs:documentation>
                        The parameter can be repeated or omitted.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Example">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="client" type="ExampleClientToServer" />
            <xs:element name="server" type="ExampleServerToClient" />
            <xs:element name="later" type="ExampleLater" />
            <xs:element name="remark" type="Markdown" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ExampleMessage" mixed="true">
        <xs:sequence>
            <xs:element name="remark" type="Markdown" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ExampleClientToServer">
        <xs:annotation>
            <xs:documentation>
                One message sent from client to server (request).
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="ExampleMessage" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ExampleServerToClient">
        <xs:annotation>
            <xs:documentation>
                One message sent from server to client (response).
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="ExampleMessage" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ExampleLater">
        <xs:annotation>
            <xs:documentation>
                Some time passes between messages.
            </xs:documentation>
        </xs:annotation>
        <xs:all />
    </xs:complexType>

    <!--
    <xs:complexType name="ExampleRemark">
        <xs:annotation>
            <xs:documentation>
                Annotates the example to provide additional explanations/conditions describing the behaviour. Can be used either at the end of a message or in between messages.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="xs:string" />
        </xs:complexContent>
    </xs:complexType>
    -->

    <xs:complexType name="Markdown">
        <!-- TODO: is language injection for Intellij possible to be defined by XMLSchema? -->
        <xs:simpleContent>
            <xs:extension base="xs:string" />
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== dneuge/xprc-protocol/src/commands/xpcommand/cmtr.xml
<?xml version="1.0" encoding="UTF-8"?>
<command name="CMTR" title="Trigger Command" group="xpcommand"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../command.xsd">
    <mnemonic><m>C</m>o<m>m</m>mand <m>T</m><m>r</m>igger</mnemonic>
    <description>
        Triggers the given X-Plane command(s).

        The command can also be held "down" temporarily in which case an unknown number of retrigger events may occur.
        The effect of such held commands is defined by X-Plane and individual command implementations. X-Plane commands
        held during XPRC command termination are released on the next flight-loop cycle.

        If a specific number of trigger events is needed, the command should be immediately released again
        (`hold` not set or `0`) and retriggered via `times=n` and an appropriate `repeatFreq`. For held commands, it is
        not possible to monitor the actual number of resulting `TRIGGER` events.

        The reason for this behavior is that X-Plane API submits three events to commands but allows only two of them
        to be directly controlled:

        * `XPLMCommandBegin` starts holding the command, leading to event `xplm_CommandBegin` (XPRC: `HOLD`)
        * `XPLMCommandEnd` stops holding it, leading to `xplm_CommandEnd` (XPRC: `RELEASE`)

        The event `xplm_CommandContinue` (XPRC: `TRIGGER`) is issued by X-Plane
        * once when the command begins to be held
        * repeatedly while the command is being held, after an initial delay

        How often X-Plane triggers can only be controlled by immediately releasing the command again (or using
        `XPLMCommandOnce` on the API).
    </description>
    <options>
        <option name="hold" variableName="X" default="0f" defaultRemark="trigger with immediate release, like `XPLMCommandOnce`">
            <description>time to hold the command</description>
            <suffixes>
                <suffix name="ms">
                    milliseconds

                    Command will be released on the first frame matching or exceeding the requested time measured
                    from start of cycle or when a repetition occurs (whichever is first).
                </suffix>
                <suffix name="f">
                    frames

                    Command will be released on the exact frame requested or when a repetition occurs.
                </suffix>
            </suffixes>
        </option>
        <option name="repeatFreq" variableName="X" default="1f">
            <description>
                repeat in intervals of X

                Repetition intervals are based on time passed since start of command (no clock skew).
            </description>
            <suffixes>
                <suffix name="ms">milliseconds</suffix>
                <suffix name="f">frames</suffix>
            </suffixes>
        </option>
        <option name="times" variableName="n" default="1" defaultRemark="only once">
            <description>
                repeat given number of times

                * set to `infinite` for infinite repeat (only stopped by `TERM` or disconnect)
            </description>
        </option>
        <option name="monitor" default="cycle">
            <description>
                controls feedback about command invocations
            </description>
            <constants>
                <constant name="holdRelease">
                    notifies about each invocation of:

                    * `HOLD` (according to X-Plane API `XPLMCommandBegin`)
                    * `RELEASE` (according to X-Plane API `XPLMCommandEnd`)
                </constant>
                <constant name="cycle">
                    notifies only about each start of repetition by `CYCLE` (equal to `HOLD` but without `RELEASE`)
                </constant>
                <constant name="none">
                    disables monitoring
                </constant>
            </constants>
        </option>
        <!-- TODO: add phase option? -->
    </options>
    <parameters>
        <parameter multiplicity="+">
            command name

            Providing multiple command names will cause them to be triggered within the same frame.
            All commands are triggered in the specified order.
            If commands are being held (using `XPLMCommandBegin` on X-Plane API) they will be released in reverse order.
        </parameter>
    </parameters>
    <responses>
        <response>
            status
            * If any command cannot be found: `ERR`
            * Otherwise: `ACK`
        </response>
        <response>
            Depending on `monitor` option:
            * if `monitor=holdRelease`:
              * `HOLD` as `XPLMCommandBegin` is being invoked by the server
              * `RELEASE` as `XPLMCommandEnd` is being invoked by the server
            * if `monitor=cycle`:
              * `CYCLE` on each repetition as `XPLMCommandBegin` is being invoked by the server
        </response>
    </responses>
    <notes>
        <note>
            While repetition intervals are based on the original start of XPRC command, the time of releasing the
            XP command when using a time-based `hold` option is always measured relative to the start of holding
            the XP command (not the time of the XPRC command having been received) to not shorten the requested
            duration.
        </note>
    </notes>
</command>

=== dneuge/xprc-protocol/src/commands/dataref/drls.xml
<?xml version="1.0" encoding="UTF-8"?>
<command name="DRLS" title="List DataRefs" group="dataref"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../command.xsd">
    <mnemonic><m>D</m>ata<m>R</m>ef <m>L</m>i<m>s</m>t</mnemonic>
    <description>
        Lists information about available datarefs. The command allows retrieval of information about specific datarefs as well as listing all datarefs known to X-Plane (unspecific). Unspecific retrieval depends on X-Plane 12.04 APIs or workarounds in case of previous versions. If unspecific retrieval is requested but not supported, servers should reply with an error status.
    </description>
    <options>
        <option name="rwCheck" default="simulator">
            <description>
                Use the read-only/read-write flag available from X-Plane or check for internal permissions available to datarefs claimed by XPRC?
            </description>
            <constants>
                <constant name="simulator">
                    use the flag published on X-Plane (may give a false `ro` indication for datarefs claimed by XPRC)
                </constant>
                <constant name="server">
                    if the dataref is claimed by XPRC, check for general availability in XPRC
                </constant>
                <constant name="session">
                    if the dataref is claimed by XPRC, check for the current session
                </constant>
            </constants>
        </option>
    </options>
    <parameters>
        <parameter multiplicity="*">Dataref name (string) to retrieve information for. If no names are provided, all available datarefs are listed (unspecific query).</parameter>
    </parameters>
    <responses>
        <response>Status: `ACK` if requested listing is technically possible, `ERR` if not</response>
        <response>
            one dataref definition per message; fields separated by semicolon:
            1. comma-separated list of supported data types (see DataRef Types)
            2. `ro` if indicated as read-only, `rw` if indicated as writable
            3. name of DataRef

            > [!note]
            > If information about specific datarefs has been requested but some (or all) of them are not found within X-Plane, the returned list may be incomplete. A completely empty result (e.g. `+ACK` followed by `-ACK`) is also possible in that case.
        </response>
    </responses>
    <examples>
        <example>
            <client>ABCD DRLS</client>
            <server>+ACK ABCD 1836</server>
            <server>+ABCD 2642 int,float,double;rw;sim/some/ref</server>
            <server>+ABCD 2642 blob;ro;something/else</server>
            <server>-ABCD 2642 int;rw;what/ever</server>
        </example>
        <example>
            <client>BBBB DRLS sim/some/ref;non/existent</client>
            <server>+ACK BBBB 3520</server>
            <server>-BBBB 3526 int,float,double;rw;sim/some/ref</server>
        </example>
        <example>
            <client>FFFF DRLS non/existent</client>
            <server>+ACK FFFF 6789</server>
            <server>-ACK FFFF 6800</server>
        </example>
        <example>
            <client>UUUU DRLS</client>
            <server>-ERR UUUU 5710 unspecific queries are not supported</server>
        </example>
    </examples>
</command>

=== dneuge/xprc-protocol/src/commands/server/srid.xml
<?xml version="1.0" encoding="UTF-8"?>
<command name="SRID" title="Server Identify" group="server"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../command.xsd">
    <mnemonic><m>S</m>e<m>r</m>ver <m>I</m><m>d</m>entify</mnemonic>
    <description>
        Queries basic information about the XPRC server.

        The server will send key/value pairs. Keys must be unique per query, order does not matter.

        While some information is mandatory to be provided by servers, clients should not expect them to always be
        present as additional keys may only be added in future protocol revisions and thus may be missing from older
        server implementations.

        Mandatory: (to be sent exactly once)

        * `name`: human-readable implementation name (do not interpret, use `id` for machine-readable information instead)
        * `id`: server implementation ID (recommended for global uniqueness: based on an Internet domain, e.g. reversed domain name of repository or website)
        * `version`: implementation-specific version string (interpret only as documented by server implementation)

        Optional: (keys sent at most once)

        * `apiversion`: XPLM version currently used by XPRC as returned by 'XPLMGetVersions'
        * `website`: URL to website for more information about server implementation (not the server instance, meant for users; use `id` if identification is needed)
        * `xpversion`: X-Plane version currently running XPRC as returned by 'XPLMGetVersions'
        * keys prefixed `x-`: implementation-specific extra information (interpret only as documented by server implementation)
          * servers should use a stable/compatible format once introduced and are recommended not to change meaning of keys
          * clients/applications are recommended to not only check `id` but also `version` before interpreting these entries
    </description>
    <responses>
        <response>
            status, always `ACK`
        </response>
        <response>
            Multiple messages, each holding a key/value pair as described above. Keys are separated by colon `:` from values.
        </response>
    </responses>
    <examples>
        <example>
            <client>AAAA SRID</client>
            <server>+ACK AAAA 6723</server>
            <server>+AAAA 6723 id:org.codeberg.dneuge.xprc-example-server</server>
            <server>+AAAA 6723 name:Fictional Example Implementation</server>
            <server>+AAAA 6723 version:1.3 RC4</server>
            <server>+AAAA 6723 website:https://codeberg.org/dneuge/xprc-example-server</server>
            <server>+AAAA 6723 xpversion:12400</server>
            <server>+AAAA 6723 apiversion:421</server>
            <server>-AAAA 6723 x-build-id:3612</server>
        </example>
    </examples>
    <notes>
        <note>
            Servers may choose to either combine status responses with the first key-value pair or issue a blank `ACK`
            for improved readability of the first pair as shown in the example.
        </note>
    </notes>
</command>
