=== dneuge/xprc-protocol/src/command.xsd
<?xml version='1.0' encoding='utf-8' ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--xs:import namespace="http://www.w3.org/XML/1998/namespace" /-->

    <xs:element name="command" type="Command">
        <xs:annotation>
            <xs:documentation>
                Describes a single command for protocol user documentation.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="Command">
        <xs:all>
            <xs:element name="mnemonic" type="Mnemonic">
                <xs:annotation>
                    <xs:documentation>
                        Describes how the command name is derived from a mnemonic description.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="Markdown">
                <xs:annotation>
                    <xs:documentation>
                        Main description; should provide an overview of what the command does and is intended for. Should not go into details regarding options or parameters. Side-effects and conditions may make sense to be described as notes instead to be more visible.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="options" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="option" type="Option" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="parameters" type="Parameters" minOccurs="0" />
            <xs:element name="responses">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="response" type="Markdown" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="notes" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Additional notes to be shown as bullet items.
                    </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="note" type="Markdown" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="examples" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="example" type="Example" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>

        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="title" type="xs:string" />
        <xs:attribute name="group" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Mnemonic" mixed="true">
        <xs:sequence>
            <xs:element name="m" type="xs:string" minOccurs="4" maxOccurs="4" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Option">
        <xs:sequence>
            <xs:element name="description" type="Markdown" />
            <xs:element name="suffixes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="suffix" type="OptionSuffix" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="constants" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="constant" type="OptionConstant" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="default" type="xs:string" />
        <xs:attribute name="defaultRemark" type="xs:string" />
        <xs:attribute name="variableName" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="OptionSuffix">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="OptionConstant">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Parameters">
        <xs:sequence>
            <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="subparameters" type="SubParameters" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SubParameters">
        <xs:sequence>
            <xs:element name="subparameters" type="SubParameters" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="delimiter" type="xs:string" />
        <xs:attribute name="multiplicity" default="1" type="ParameterMultiplicity" />
        <xs:attribute name="condition" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="multiplicity" default="1" type="ParameterMultiplicity" />
                <xs:attribute name="condition" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="ParameterMultiplicity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="?">
                <xs:annotation>
                    <xs:documentation>
                        The parameter is optional.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
                <xs:annotation>
                    <xs:documentation>
                        The parameter occurs exactly once.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="+">
                <xs:annotation>
                    <xs:documentation>
                        The parameter occurs at least once, can be repeated immediately afterwards.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="*">
                <xs:annotation>
                    <xs:documentation>
                        The parameter can be repeated or omitted.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Example">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="client" type="ExampleClientToServer" />
            <xs:element name="server" type="ExampleServerToClient" />
            <xs:element name="later" type="ExampleLater" />
            <xs:element name="remark" type="Markdown" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ExampleMessage" mixed="true">
        <xs:sequence>
            <xs:element name="remark" type="Markdown" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ExampleClientToServer">
        <xs:annotation>
            <xs:documentation>
                One message sent from client to server (request).
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="ExampleMessage" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ExampleServerToClient">
        <xs:annotation>
            <xs:documentation>
                One message sent from server to client (response).
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="ExampleMessage" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ExampleLater">
        <xs:annotation>
            <xs:documentation>
                Some time passes between messages.
            </xs:documentation>
        </xs:annotation>
        <xs:all />
    </xs:complexType>

    <!--
    <xs:complexType name="ExampleRemark">
        <xs:annotation>
            <xs:documentation>
                Annotates the example to provide additional explanations/conditions describing the behaviour. Can be used either at the end of a message or in between messages.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="xs:string" />
        </xs:complexContent>
    </xs:complexType>
    -->

    <xs:complexType name="Markdown">
        <!-- TODO: is language injection for Intellij possible to be defined by XMLSchema? -->
        <xs:simpleContent>
            <xs:extension base="xs:string" />
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== dneuge/xprc-protocol/src/commands/server/srlc.xml
<?xml version="1.0" encoding="UTF-8"?>
<command name="SRLC" title="List Server Commands" group="server"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../command.xsd">
    <mnemonic><m>S</m>e<m>r</m>ver <m>L</m>ist <m>C</m>ommands</mnemonic>
    <description>
        Queries information about commands implemented by the XPRC server.

        Each message sent by the server describes one command. Although recommended to provide a complete listing,
        servers may not describe all commands they implement (in particular, some experimental commands intended only
        for internal use may be omitted). Apart from the first message being required to describe `SRLC`, all other
        commands are listed in no specific order. Commands must only be listed at most once per request (no repetition).

        Commands starting with `X` are server-specific and should not be used unless their meaning has been confirmed,
        see the section on "experimental commands" for details.

        `SRFS` should not be used simultaneously as the result of `SRLC` may be inconsistent/outdated at the time it is
        being received. Applications are recommended to check (and if necessary reconfigure) commands/features once
        when initiating connections.

        Clients are advised to only interpret the response if they support the indicated `SRLC` version and its active
        feature flags.

        See the section on "feature versioning" for details.

        All command descriptions are formatted as (delimited by colon):

        1. command name
        2. currently active command version as unsigned integer
           * initially, latest supported version must be active (may be switched via `SRFS`, if supported)
           * `0` if version is unavailable (e.g. on unversioned experimental commands)
        3. list of command feature flags, separated by comma; each feature flag is formatted as: (may be omitted if empty)
           1. feature status
              * `*` enabled by default (can be disabled)
              * `?` disabled by default (can be enabled)
              * `+` enabled as requested (can be disabled again)
              * `-` disabled as requested (can be enabled again)
              * `/` if unavailable (cannot be enabled)
              * omitted if always enabled (cannot be disabled)
           2. feature flag name
              * one or more basic alpha-numeric characters incl. `-`, case sensitive (regular expression: `[a-zA-Z0-9\-]+`)
              * `x-` should be used as a prefix to server-specific flags
    </description>
    <responses>
        <response>
            status, always `ACK`
        </response>
        <response>
            First message always describes `SRLC` command (see above for details).
        </response>
        <response>
            One message per described command (see above for details).
        </response>
    </responses>
    <examples>
        <example>
            <client>AAAA SRLC</client>
            <server>+ACK AAAA 153</server>
            <server>+AAAA 153 SRLC:1</server>
            <server>+AAAA 153 XRND:3:/seed,?secure<remark>fictional command, also see `SRFS` examples</remark></server>
            <server>+AAAA 153 XCLS:0</server>
            <server>+AAAA 153 DRLS:1:unspecific</server>
            <later/>
            <server>-AAAA 153 DRQV:1</server>
        </example>
    </examples>
</command>
