=== dneuge/xprc-protocol/src/command.xsd
<?xml version='1.0' encoding='utf-8' ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--xs:import namespace="http://www.w3.org/XML/1998/namespace" /-->

    <xs:element name="command" type="Command">
        <xs:annotation>
            <xs:documentation>
                Describes a single command for protocol user documentation.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="Command">
        <xs:all>
            <xs:element name="mnemonic" type="Mnemonic">
                <xs:annotation>
                    <xs:documentation>
                        Describes how the command name is derived from a mnemonic description.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="Markdown">
                <xs:annotation>
                    <xs:documentation>
                        Main description; should provide an overview of what the command does and is intended for. Should not go into details regarding options or parameters. Side-effects and conditions may make sense to be described as notes instead to be more visible.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="options" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="option" type="Option" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="parameters" type="Parameters" minOccurs="0" />
            <xs:element name="responses">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="response" type="Markdown" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="notes" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Additional notes to be shown as bullet items.
                    </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="note" type="Markdown" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="examples" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="example" type="Example" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>

        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="title" type="xs:string" />
        <xs:attribute name="group" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Mnemonic" mixed="true">
        <xs:sequence>
            <xs:element name="m" type="xs:string" minOccurs="4" maxOccurs="4" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Option">
        <xs:sequence>
            <xs:element name="description" type="Markdown" />
            <xs:element name="suffixes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="suffix" type="OptionSuffix" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="constants" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="constant" type="OptionConstant" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="default" type="xs:string" />
        <xs:attribute name="defaultRemark" type="xs:string" />
        <xs:attribute name="variableName" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="OptionSuffix">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="OptionConstant">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Parameters">
        <xs:sequence>
            <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="subparameters" type="SubParameters" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SubParameters">
        <xs:sequence>
            <xs:element name="subparameters" type="SubParameters" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="delimiter" type="xs:string" />
        <xs:attribute name="multiplicity" default="1" type="ParameterMultiplicity" />
        <xs:attribute name="condition" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="multiplicity" default="1" type="ParameterMultiplicity" />
                <xs:attribute name="condition" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="ParameterMultiplicity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="?">
                <xs:annotation>
                    <xs:documentation>
                        The parameter is optional.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
                <xs:annotation>
                    <xs:documentation>
                        The parameter occurs exactly once.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="+">
                <xs:annotation>
                    <xs:documentation>
                        The parameter occurs at least once, can be repeated immediately afterwards.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="*">
                <xs:annotation>
                    <xs:documentation>
                        The parameter can be repeated or omitted.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Example">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="client" type="ExampleClientToServer" />
            <xs:element name="server" type="ExampleServerToClient" />
            <xs:element name="later" type="ExampleLater" />
            <xs:element name="remark" type="Markdown" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ExampleMessage" mixed="true">
        <xs:sequence>
            <xs:element name="remark" type="Markdown" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ExampleClientToServer">
        <xs:annotation>
            <xs:documentation>
                One message sent from client to server (request).
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="ExampleMessage" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ExampleServerToClient">
        <xs:annotation>
            <xs:documentation>
                One message sent from server to client (response).
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="ExampleMessage" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ExampleLater">
        <xs:annotation>
            <xs:documentation>
                Some time passes between messages.
            </xs:documentation>
        </xs:annotation>
        <xs:all />
    </xs:complexType>

    <!--
    <xs:complexType name="ExampleRemark">
        <xs:annotation>
            <xs:documentation>
                Annotates the example to provide additional explanations/conditions describing the behaviour. Can be used either at the end of a message or in between messages.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="xs:string" />
        </xs:complexContent>
    </xs:complexType>
    -->

    <xs:complexType name="Markdown">
        <!-- TODO: is language injection for Intellij possible to be defined by XMLSchema? -->
        <xs:simpleContent>
            <xs:extension base="xs:string" />
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== dneuge/xprc-protocol/src/commands/dataref/drmu.xml
<?xml version="1.0" encoding="UTF-8"?>
<command name="DRMU" title="Manipulate DataRefs Uncontrolled" group="dataref"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../command.xsd">
    <mnemonic><m>D</m>ata<m>R</m>ef <m>M</m>anipulate <m>U</m>ncontrolled</mnemonic>
    <description>
        Sets datarefs to the requested values, either immediately or progressively over time.
        "Uncontrolled" means that apart from the initial value no feedback will be incorporated into the (intermediate)
        values being set (as compared to a PID controller or similar).
        By not incorporating any feedback, simultaneous manipulation of values may result in noticeably
        (possibly unstable) jumping values.

        Depending on server implementation, datarefs that are owned by the XPRC server may be manipulated asynchronously
        outside X-Plane flight loop phases but generally only if:

        * application is immediate, no timing is requested; i.e. `method=immediate` and `repeatFreq` is not set/single run
        * all datarefs to be manipulated are owned by the same XPRC server instance

        Server implementations are recommended but not required to enable asynchronous manipulation in these cases.
    </description>
    <options>
        <option name="repeatFreq" variableName="X" default="0" defaultRemark="single run only">
            <description>repeat in intervals of X</description>
            <suffixes>
                <suffix name="ms">milliseconds</suffix>
                <suffix name="f">frames</suffix>
            </suffixes>
        </option>
        <!-- TODO: currently no parameter for number of repetitions is specified; add?
        <option name="times" defaultRemark="infinite, until terminated" variableName="n">
            <description>
                number of times to update; command will terminate after `n` retrievals
            </description>
        </option>
        -->
        <option name="method" default="immediate">
            <description>
                how to set the value
            </description>
            <constants>
                <constant name="immediate">
                    immediately set to the requested value (only valid option for blobs)
                </constant>
                <constant name="linear">
                    linear modification from original to requested value
                </constant>
            </constants>
        </option>
        <!-- TODO: currently not implemented (was prepared but commented out - still needed?), marked "under review for removal" in latest pre-XML spec
        <option name="methodFreq" variableName="X" default="1f" defaultRemark="each frame">
            <description>set progressively in intervals of X (no effect if `method` is `immediate`)</description>
            <suffixes>
                <suffix name="ms">milliseconds</suffix>
                <suffix name="f">frames</suffix>
            </suffixes>
        </option>
        -->
        <option name="duration" default="2500ms">
            <description>
                controls the duration of each manipulation cycle, no effect if `method` is `immediate`

                Actual duration depends on flight loop calls (frames in XP).
            </description>
            <suffixes>
                <suffix name="ms">milliseconds</suffix>
                <suffix name="f">frames</suffix>
            </suffixes>
        </option>
        <option name="monitor" default="none">
            <description>
                controls if and which feedback should be sent back to the channel

                Array ranges are based on the requested start index and limited to the length used, only partial arrays
                will be returned for `set` mode. `get` mode may return a shorter actual length (as remaining from the
                requested index) depending on actual dataref content.
            </description>
            <constants>
                <constant name="set">
                    send the currently set value(s) on each update
                </constant>
                <constant name="get">
                    sends what the dataref actually returns after setting on each update
                </constant>
                <constant name="none">
                    only acknowledge command and close channel when done
                </constant>
            </constants>
        </option>
        <option name="phase" defaultRemark="don't care">
            <description>
                when to write the value
            </description>
            <constants>
                <constant name="0">
                    before flight model
                </constant>
                <constant name="1">
                    after flight model
                </constant>
            </constants>
        </option>
    </options>
    <parameters>
        <subparameters multiplicity="+" delimiter=":">
            <parameter>value type</parameter>
            <parameter>name of the requested dataref</parameter>
            <parameter multiplicity="?" condition="optionally, if array or blob">
                `[i]` to set only values from index `i` (`i=0` is the first element; default=`0`)
            </parameter>
            <parameter>
                value(s) to set, encoded as explained in the Dataref Types section

                Array ranges can be written to by only providing a partial array; e.g. addressing index `[4]` on a
                10 item array and passing a value of length `2` will only manipulate indexes 4 and 5 while leaving
                0..3 and 6..9 unchanged.
            </parameter>
            <parameter multiplicity="?">
                value(s) to start from, encoded as explained in the DataRef Types section (optional)

                * If not set, the start value will be read from actual dataref at each start of repetition.
                * Array ranges are handled in the same way as the target value parameter, length has to match.
            </parameter>
        </subparameters>
    </parameters>
    <responses>
        <response>
            status
            * If any dataref cannot be found or any type is unavailable: `ERR`
            * Otherwise: `ACK`
        </response>
        <response>
            Only if `monitor` was requested: intermediate values at referenced time
            * semicolon-separated in same order as requested
            * see dataref type descriptions for value encoding
        </response>
    </responses>
    <notes>
        <note>
            When choosing another `method` than `immediate`, all intermediate values will be calculated relative to the
            time passed since start of command/repetition.
        </note>
        <note>
            Repetition intervals are based on time passed since start of command (no clock skew).
        </note>
        <note>
            If base values are not fixed, they will be read on each first iteration of a repetition. However, the values
            to be set by the same iteration are already calculated with the time passed since calculated start of the
            command/repetition.
        </note>
        <note>
            If base values are fixed, the initial base value is already outdated by the time a new repetition is
            initialized; it will be adjusted according to the time passed since calculated restart.
        </note>
        <note>
            If a repetition interval (`repeatFreq`) is met before the previous cycleâ€™s `duration` concludes, the
            previous cycle's end value will not be set. Instead the new cycle starts applying values seamlessly as per
            the previous note.
        </note>
        <note>
            Datarefs flagged as read-only through X-Plane API may (and will be attempted to) still be written to.
            Internally hosted datarefs (see `DRCI`) are known to be actually restricted and are checked during command
            creation but not afterwards.
            During creation, internally write-protected DataRefs will fail command creation.
        </note>
        <note>
            When accessing internally hosted datarefs (see `DRCI`):

            * Internal availability of datarefs is only checked during command creation.
            * If a dataref becomes unclaimed, the dataref will still be attempted to be accessed through X-Plane
              (the command continues to run).
            * If a dataref becomes claimed (again), the dataref will still be accessed through X-Plane. Write-protected
              datarefs will fail to be written to unless the command is restarted.
        </note>
    </notes>
    <examples>
        <example>
            <client>ABCD DRMU;repeatFreq=5000ms int:some/value:2;float:other/name:3.2</client>
            <server>+ACK ABCD 5412<remark>command stays active and sets both values immediately every 5 seconds until terminated</remark></server>
            <server>ABCD TERM<remark>also stops periodic resets</remark></server>
            <server>-ACK ABCD 15741</server>
        </example>
        <example>
            <client>xyz1 DRMU;method=linear;monitor=set;duration=1000ms int:some/ref:1000</client>
            <server>+ACK xyz1 6402</server>
            <server>+xyz1 6432 102<remark>server sends monitored values as they are being set</remark></server>
            <server>+xyz1 6480 243</server>
            <server>+xyz1 6504 310</server>
            <later />
            <server>+xyz1 7413 987</server>
            <server>-xyz1 7435 1000</server>
            <remark>
                target value (`1000`) has been set after requested `duration` of `1000ms`, channel closed (no repetition)
            </remark>
        </example>
    </examples>
</command>

=== dneuge/xprc-protocol/src/commands/server/srfs.xml
<?xml version="1.0" encoding="UTF-8"?>
<command name="SRFS" title="Select Server Features" group="server"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../command.xsd">
    <mnemonic><m>S</m>e<m>r</m>ver <m>F</m>eature <m>S</m>elect</mnemonic>
    <description>
        Reconfigures a single command by changing feature flags and/or switching command versions.

        See the section on "feature versioning" for details.

        Servers may not allow any changes to be made. The command should still be implemented as a placeholder always
        indicating an error (`ERR`) status in that case.

        Servers should never punish clients for errors caused by legit `SRFS` requests.

        Changing versions may reset feature flags to the command version's default.

        Clients are recommended to check `SRLC` before using this command and verify actual features by requesting
        `SRLC` again after all `SRFS` requests have been completed.

        `SRLC` and `SRFS` should not be used simultaneously to avoid inconsistent/outdated information but multiple
        `SRFS` commands may be issued in parallel.
    </description>
    <parameters>
        <parameter>command name</parameter>
        <parameter>requested command version (using currently active version must not reset feature flags)</parameter>
        <subparameters multiplicity="*" delimiter="," condition="can be omitted if no feature flags should be changed">
            <parameter>
                change of flag, consisting of: (concatenated without space)

                1. requested state of feature flag:
                   * `+` to enable the feature flag
                   * `-` to disable the feature flag
                2. name of feature flag to change
            </parameter>
        </subparameters>
    </parameters>
    <responses>
        <response>
            status

            * if requested command version and changes to feature flags are effective from now on: `ACK`
            * if any requested change is not supported/possible: `ERR`
        </response>
    </responses>
    <examples>
        <example>
            <client>AAAA SRFS XRND;3;+secure<remark>see `SRLC` example</remark></client>
            <server>-ACK AAAA 654</server>
        </example>
        <example>
            <client>AAAA SRFS XRND;3;-secure</client>
            <server>-ACK AAAA 694</server>
        </example>
        <example>
            <client>AAAA SRFS XRND;2</client>
            <server>-ACK AAAA 712</server>
        </example>
        <example>
            <client>AAAA SRFS XRND;1</client>
            <server>-ERR AAAA 764 command version not supported: 1</server>
        </example>
        <example>
            <client>AAAA SRFS XRND;3;+iter</client>
            <server>-ERR AAAA 794 unknown feature flag: "iter"</server>
        </example>
        <example>
            <client>AAAA SRFS XRND;3;+seed</client>
            <server>-ERR AAAA 811 "seed" feature is unavailable on this server</server>
        </example>
        <example>
            <client>AAAA SRFS XRND;3;+secure,-seed</client>
            <server>-ACK AAAA 832</server>
        </example>
        <example>
            <client>AAAA SRFS XRND;3;+secure</client>
            <server>+ACK AAAA 867<remark>note that channel stays open; reconfiguration could not be finished instantly</remark></server>
            <server>-ERR AAAA 982<remark>the requested change actually fails after a short time</remark></server>
        </example>
    </examples>
    <notes>
        <note>
            Do not mistake channel acknowledgement for a success indicator: As with all other commands, `SRFS` has only
            finished successfully once the channel was closed without any error indication.
        </note>
    </notes>
</command>

=== dneuge/xprc-protocol/src/commands/xpcommand/cmhd.xml
<?xml version="1.0" encoding="UTF-8"?>
<command name="CMHD" title="Hold Command" group="xpcommand"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../command.xsd">
    <mnemonic><m>C</m>o<m>m</m>mand <m>H</m>ol<m>d</m></mnemonic>
    <description>
        Holds the given X-Plane command(s) until terminated.

        In X-Plane API this corresponds to `XPLMCommandBegin` with `XPLMCommandEnd` only sent on `TERM` or disconnect.
        X-Plane (on its own) will continuously issue trigger events while being held.

        Note that XPRC command termination may be acknowledged before actual release of the X-Plane command being held.
    </description>
    <parameters>
        <parameter multiplicity="+">
            command name

            Providing multiple command names will cause them to be held and released within the same frames.
            All commands begin to be held in the specified order and will be released in reverse order.
        </parameter>
    </parameters>
    <responses>
        <response>
            status
            * If any command cannot be found: `ERR`
            * Otherwise: `ACK`
        </response>
    </responses>
</command>

=== dneuge/xprc-protocol/src/commands/xpcommand/cmrg.xml
<?xml version="1.0" encoding="UTF-8"?>
<command name="CMRG" title="Register Command" group="xpcommand"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../command.xsd">
    <mnemonic><m>C</m>o<m>m</m>mand <m>R</m>e<m>g</m>ister</mnemonic>
    <!-- TODO: SDK Docs say: "You can register a single callback both before and after a command."
           What happens if multiple command handlers are attempted to be registered and unregistered in another order? (Later registration ignored? Crash?)
           Can previous registration outside of XPRC be detected?
           Should XPRC handle multiple registrations internally or fail the command? -->
    <description>
        Registers a new handler for the specified X-Plane command.

        The command will be created if it does not already exist in X-Plane. Each received call will be forwarded.
        XPRC does not react to the invocation on its own. The handler will be unregistered on termination.
    </description>
    <options>
        <option name="monitor" default="all">
            <description>
                controls feedback about command invocations
            </description>
            <constants>
                <constant name="all">notifications are sent for all events</constant>
                <constant name="trigger">notifications will only be sent for "trigger" events (not "hold" or "release")</constant>
                <constant name="holdRelease">notifications will only be sent for "hold" and "release" events (omitting "trigger" events)</constant>
            </constants>
        </option>
        <option name="propagate" default="false">
            <description>
                whether to allow or stop propagation to further command handlers
            </description>
            <constants>
                <constant name="true">other handlers can continue processing the events</constant>
                <constant name="false">events are stopped from propagation to other handlers</constant>
            </constants>
        </option>
        <option name="phase" default="before">
            <description>
                when to be called
            </description>
            <constants>
                <constant name="before">before X-Plane-internal handler</constant>
                <constant name="after">after X-Plane-internal handler</constant>
            </constants>
        </option>
    </options>
    <parameters>
        <parameter>command name</parameter>
        <parameter multiplicity="?">
            command description (can only be set during initial command creation)
        </parameter>
    </parameters>
    <responses>
        <response>
            status
            * If registration fails: `ERR`
            * Otherwise: `ACK`
        </response>
        <response>
            On each invocation, according to `monitor` option:
            * `HOLD` as command starts being held (`xplm_CommandBegin` being received by server)
            * `TRIGGER` as command is being triggered (`xplm_CommandContinue` being received by server)
            * `RELEASE` as command is being released (`xplm_CommandEnd` being received by server)
        </response>
    </responses>
</command>
